config/routes.rb
WebadapterPrototype::Application.routes.draw do

  devise_for :users

  resources :sites do
    get 'page/:page', :action => :index, :on => :collection
    match 'api/:name', :to => "api_methods#call", :as => 'api_method_call'

    resources :api_methods do
      member do
        get 'call'
      end

      resources :versions do
        member do
          put 'restore'
        end
      end

      resources :alarms
    end

    member do
      put :archive
      put :unarchive
    end

    collection do
      get :archived
    end

  end

  resources :users do
    member do
      put :disable
      put :enable
    end
  end

  resources :alarms

  root :to => 'sites#index'
end

app/models/api_method.rb
require_dependency 'script'

class ApiMethod < ActiveRecord::Base
  belongs_to :site
  has_many :script_versions, :dependent => :destroy
  has_many :alarms, :dependent => :destroy

  attr_accessible :name, :script, :site_id, :draft
  validates_presence_of :name
  validates_format_of :name, :with => /^[\w\d\-]+$/, :message => "can only contain letters, numbers and -"
  validates_uniqueness_of :name, :scope => :site_id

  validates_associated :site

  def save_version(params)
    user = params[:user]
    message = params[:message]
    raise ArgumentError, "no user specified" unless user
    raise ArgumentError, "no message specified" unless message
    transaction do
      self.save!
      self.script_versions.create!(:user => user, :message => message, :script => self.script)
    end
  end

  def save_draft(new_draft)
    if clean_extra_whitespace(new_draft) != clean_extra_whitespace(self.script)
      update_attributes({:draft => new_draft})
    end
  end

  def draft_diff
    Differ.diff_by_word(self.script, self.draft).format_as(:html)
  end

  def clean_extra_whitespace(str)
    str.to_s.strip.gsub(/[\r\n]+/, "\n").gsub(/\s+/, " ")
  end

  def clear_draft
    self.draft = nil
  end

  def draft?
    self.draft && !self.draft.empty?
  end

  def run_script(request_params, remote_session)
    script = Script.new(self.script)
    script.run({ :params => request_params, :remote_session => remote_session })
    if script.alarm_raised?
      Alarm.create_or_increment!(:api_method => self, :message => script.error, :remote_session => remote_session)
    end

    if script.successful?
      remote_session.success!(self.id)
    end
    script
  end

  def load_default_script_if_required
    if script.blank?
      script_file = File.join(Rails.root, "config", "default_script")
      self.script = File.read(script_file)
    end
  end

end

app/controllers/api_methods_controller.rb
class ApiMethodsController < ApplicationController

  before_filter :load_site
  skip_before_filter :authenticate_user!, :only => [:call]

  def show
    @api_method = @site.api_methods.find(params[:id])
    @api_method.load_default_script_if_required
    render :layout => "ide"
  end

  def new
    @api_method = @site.api_methods.new
  end

  def create
    @api_method = @site.api_methods.new(params[:api_method])
    if @api_method.save
      flash[:notice] = "Yay! Api method created!"
      redirect_to [@site, @api_method]
    else
      flash[:error] = ":( Something went wrong try again later, maybe tomorrow!"
      render :new
    end
  end

  def edit
    @api_method = @site.api_methods.find(params[:id])
  end

  def update
    @api_method = @site.api_methods.find(params[:id])
    @api_method.clear_draft

    @api_method.attributes = params[:api_method]
    if @api_method.script_changed? && @api_method.save_version(:user => current_user, :message => params[:message])
      flash[:notice] = "Yay! Script saved!"
      redirect_to [@site, @api_method]
    elsif @api_method.save
      flash[:notice] = "Yay! Api method updated!"
      redirect_to [@site, @api_method]
    else
      flash[:error] = ":( Something went wrong try again later, maybe tomorrow!"
      render :edit
    end
  end

  def call
    if @site.archived?
      render :json => { :error => "Site archived" }, :status => 422 and return
    end
    remote_session = RemoteSession.get(session[:remote_session_id])
    session[:remote_session_id] = remote_session.id

    @api_method = @site.api_methods.find_by_name(params[:name])
    if params[:script]
      script = params[:script]
      @api_method.save_draft( script )
      @api_method.script = script
    end

    params_to_delete = [:controller, :action, :script]
    safe_params = params.dup.delete_if { |p| params_to_delete.include?(p.to_sym) }
    
    script = @api_method.run_script(safe_params, remote_session)
    if script.successful?
      if script.result.nil? && script.warning
        render :json => { :warning => script.warning }
      else
        Stats.new(@api_method.id).store(script.stats[:total])
        render :json => { :result => script.result, :debug => script.debug, :stats => script.stats }
      end
    else
      render :json => { :error => script.error, :line => script.line }, :status => 422
    end
  end

  def destroy
    @api_method = @site.api_methods.find(params[:id])
    @api_method.destroy
    redirect_to @site
  end

  protected

  def load_site
    @site = Site.find(params[:site_id])
  end

end

app/views/api_methods/_form.html.erb
<div class="control-group">
  <label class="control-label" for="site_name">Name:
  </label>
  <div class="controls">
    <%= form.text_field :name, :class => "input-xlarge", :autofocus => true %>
      <p class="help-block">Name of the endpoint</p>
  </div>
</div>

app/views/api_methods/_ide.html.erb
<div id="area-wrapper">
  <%= form.text_area :script, :class => "input-xlarge" %>

  <div id="editor"></div>

</div>

app/views/api_methods/edit.html.erb
<% content_for :title, "Edit" %>

  <%= form_for [@site, @api_method], :html => {:class => "form-horizontal script-form"}  do |form| %>

    <fieldset>
      <%= render :partial => "shared/errors", locals: { object: @api_method} %>
      <%= render form %>

      <div class="form-actions">
        <button type="submit" class="btn">Save</button>
      </div>

    </fieldset>

  <% end %>

app/views/api_methods/new.html.erb
<% content_for :title, "New Api Method" %>

<%= form_for [@site, @api_method], :html => {:class => "form-horizontal"}  do |form| %>
  <fieldset>
    <%= render :partial => "shared/errors", locals: { object: @api_method} %>
    <%= render form %>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Create!</button>
    </div>
  </fieldset>
<% end %>

app/views/api_methods/show.html.erb
<% content_for :title, @api_method.name %>

<div class="row-fluid">
  <div class="span6">
    <div class="well">
      <%= render "layouts/title" %>
      <input value="<%= site_api_method_call_url(@site, :name => @api_method.name) %>" readonly="readonly" class="call-url"></input>
    </div>
  </div>
  <div class="span6">
    <p class="object-actions">
      <%= link_to [:edit, @site, @api_method], :class => "btn btn-small" do %>
      Edit
      <% end %>

      <%= link_to [@site, @api_method], :method => :delete, :confirm => "Are you sure you want to delete this Api Method? There is no way to recover it.", :class => "btn btn-small" do %>
      Delete
      <% end %>
    </p>

    <ul>
      <li><%= link_to "Versions", site_api_method_version_path(@site, @api_method, :latest) %></li>
      <li><%= link_to pluralize(@api_method.alarms.count, "alarm"), site_api_method_alarms_path(@site, @api_method) %></li>
    </ul>
  </div>
</div>


<% if @api_method.draft? %>
<div id="draft">
  <div class="row-fluid hero-unit">
    <div class="span6">
      <p>
        There is a draft copy of this script which is different from the latest saved copy. This gets created when you click 'Run' but leave the page without clicking 'Save'.
      </p>
      <p>
        What do you want to do with the draft?
      </p>
      <div class="draft-actions">
        <button id="restore" class="btn btn-success">
          Restore draft
        </button>
        <button id="discard" class="btn btn-danger" data-url="<%= site_api_method_url(@site, @api_method) %>">
          Discard draft
        </button>
        <div id="content" class="well hidden">
          <%= @api_method.draft %>
        </div>
        <div id="diff" class="well hidden">
          <%= @api_method.draft_diff.html_safe %>
        </div>
      </div>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span6">
      <h3>Latest saved copy</h3>
    </div>
    <div class="span6">
      <h3>Draft copy</h3>
    </div>
  </div>
</div>
<% end %>



<div class="row-fluid">
  <div class="span6">
    <%= form_for [@site, @api_method], :html => {:class => "form-horizontal script-form"}  do |form| %>

    <%= hidden_field_tag "message" %>

    <fieldset>
      <%= render :partial => "api_methods/ide", locals: { form: form, api_method: @api_method } %>
    </fieldset>

    <% end %>
  </div>

  <div class="span6">
    <div id="save-prompt" class="alert alert-info">
      The script has unsaved changes.
    </div>

    <div class="script-actions">
      <div id="run-script-controls">
        <input id="params" placeholder="params">

        <button id="run-script" class="btn btn-primary" data-url="<%= site_api_method_call_url(@site, :name => @api_method.name)%>">Run</button>
        <button id="start-save-script" type="submit" class="btn">Save</button>
      </div>

      <div id="save-script-controls" class="alert">
        <h4>Enter a description of what you changed in this version of the script</h4>
        <textarea id="commit-message"></textarea>
        <button id="save-script" class="btn btn-primary">Save</button>
        or
        <a href="#" id="cancel-save">cancel</a>
      </div>

      <ul id="tabbed-results" class="nav nav-tabs">
        <li class="active">
          <a data-tab="#tab-results" href="#result">Result</a>
        </li>
        <li>
          <a data-tab="#tab-debug" href="#debug">Debug</a>
        </li>
        <li>
          <a data-tab="#tab-stats" href="#stats">Stats</a>
        </li>
      </ul>
    </div>

    <div id="spinner" style="padding-top: 10px"></div>

    <div id="tab-results" class="well tabs-data">
      <pre id="result"/>
    </div>

    <div id="tab-debug" class="well tabs-data">
      <h3>Debug</h3>
      <pre>
        <ul id="debug" class="unstyled">
        </ul>
      </pre>
    </div>

    <div id="tab-stats" class="well tabs-data">
      <h3>Stats</h3>
      <pre>
        <ul id="stats" class="unstyled">
        </ul>
      </pre>
    </div>

  </div>

</div> <!-- row-fluid -->