config/routes.rb
WebadapterPrototype::Application.routes.draw do

  devise_for :users

  resources :sites do
    get 'page/:page', :action => :index, :on => :collection
    match 'api/:name', :to => "api_methods#call", :as => 'api_method_call'

    resources :api_methods do
      member do
        get 'call'
      end

      resources :versions do
        member do
          put 'restore'
        end
      end

      resources :alarms
    end

    member do
      put :archive
      put :unarchive
    end

    collection do
      get :archived
    end

  end

  resources :users do
    member do
      put :disable
      put :enable
    end
  end

  resources :alarms

  root :to => 'sites#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :enabled
  # attr_accessible :title, :body

  validates_presence_of :password_confirmation, :if => :password_required?
  
  def self.find_for_authentication(conditions)
    conditions[:enabled] = true
    find(:first, :conditions => conditions)
  end

  def disable!
    self.update_attributes(:enabled => false)
  end
  
  def enable!
    self.update_attributes(:enabled => true)
  end

  def disabled?
    !self.enabled?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.page(params[:page]).per(20)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Yay! User created!"
      redirect_to users_path
    else
      flash[:error] = "8( There was a problem while creating user"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
    if @user.update_attributes(params[:user])
      flash[:notice] = "Yay! User updated!"
      sign_in "user", @user, :bypass => true
      redirect_to users_path
    else
      flash[:error] = "8( There was a problem while updating user"
      render :edit
    end    
  end

  def disable
    @user = User.find(params[:id])
    @user.disable!
    redirect_to users_url
  end

  def enable
    @user = User.find(params[:id])
    @user.enable!
    redirect_to users_url
  end
end

app/views/users/_form.html.erb
<div class="control-group">
  <label class="control-label" for="user_email">Email:
  </label>
  <div class="controls">
    <%= form.text_field :email, :class => "input-xlarge", :autofocus => true %>
  </div>
</div>

<div class="control-group">
  <label class="control-label" for="user_password">Password:
  </label>
  <div class="controls">
    <%= form.password_field :password, :class => "input-xlarge" %>
  </div>
</div>


<div class="control-group">
  <label class="control-label" for="user_password_confirmation">Password Confirmation:
  </label>
  <div class="controls">
    <%= form.password_field :password_confirmation, :class => "input-xlarge" %>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Edit profile" %>

<%= form_for @user, :url => user_path(@user), :html => {:class => "form-horizontal"}  do |form| %>

  <fieldset>
    <%= render :partial => "shared/errors", locals: { object: @user} %> 

    <%= render :partial => "users/form", locals: { form: form} %>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Update</button>
    </div>

  </fieldset>

<% end %>

app/views/users/index.html.erb
<% content_for :title, "Users" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td>
        <% if user.enabled? %>
          <span class="label label-success">Enabled</span>
        <% else %>
          <span class="label">Disabled</span>
        <% end %>
      </td>
      <td>
      <% if user.enabled? %>
        <%= link_to "Disable", disable_user_path(user), :method => :put %>
      <% else %>
        <%= link_to "Enable", enable_user_path(user), :method => :put %>
      <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>


<ul class="primary-content">
  <li class="add">
    <%= link_to "add a user", new_user_path %>
  </li>
</ul>

<%= paginate @users %>

app/views/users/new.html.erb
<% content_for :title, "new user" %>

<%= form_for @user, :url => users_path, :html => {:class => "form-horizontal"}  do |form| %>

  <fieldset>
    <%= render :partial => "shared/errors", locals: { object: @user} %> 

    <%= render :partial => "users/form", locals: { form: form} %>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Create!</button>
    </div>

  </fieldset>

<% end %>