config/routes.rb
WebadapterPrototype::Application.routes.draw do

  devise_for :users

  resources :sites do
    get 'page/:page', :action => :index, :on => :collection
    match 'api/:name', :to => "api_methods#call", :as => 'api_method_call'

    resources :api_methods do
      member do
        get 'call'
      end

      resources :versions do
        member do
          put 'restore'
        end
      end

      resources :alarms
    end

    member do
      put :archive
      put :unarchive
    end

    collection do
      get :archived
    end

  end

  resources :users do
    member do
      put :disable
      put :enable
    end
  end

  resources :alarms

  root :to => 'sites#index'
end

app/models/site.rb
class Site < ActiveRecord::Base
  attr_accessible :name, :archived
  has_many :api_methods

  validates_presence_of :name
  validates_uniqueness_of :name

  scope :archived, where(:archived => true)
  scope :unarchived, where(:archived => false)

  def to_param
    "#{super}-#{self.name.gsub(/\s|'|\t|\/|[^a-zA-Z0-9\_\-\.]/,"-")}"
  end

  def archive
    self.update_attributes({archived: true})
  end

  def unarchive
    self.update_attributes({archived: false})
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  def index
    @sites = Site.unarchived.page(params[:page]).per(20)
  end

  def show
    @site = Site.find(params[:id])
  end

  def new
    @site = Site.new
  end

  def create
    @site = Site.new(params[:site])
    if @site.save
      flash[:notice] = "New Site created, Yay!"
      redirect_to sites_url
    else
      flash[:error] = "There was a problem creating site"
      render :new
    end
  end

  def edit
    @site = Site.find(params[:id])
  end

  def update
    @site = Site.find(params[:id])
    if @site.update_attributes(params[:site])
      flash[:notice] = "Site updated, Yay!"
      redirect_to sites_url
    else
      flash[:error] = "There was a problem while updating site"
      render :edit
    end
  end

  def destroy
    @site = Site.find(params[:id])
    @site.try(:destroy)
    redirect_to sites_url
  end

  def archived
    @sites = Site.archived.page(params[:page]).per(20)
  end

  def archive
    site = Site.find(params[:id])
    site.archive
    redirect_to archived_sites_path
  end

  def unarchive
    site = Site.find(params[:id])
    site.unarchive
    redirect_to sites_path
  end

end

app/views/sites/_form.html.erb
    <div class="control-group">
      <label class="control-label" for="site_name">Name:
      </label>
      <div class="controls">
        <%= form.text_field :name, :class => "input-xlarge", :autofocus => true %>
        <p class="help-block">Name visible in main menu</p>
      </div>
    </div>

app/views/sites/archived.html.erb
<% content_for :sidebar do %>

  <h3>Site</h3>
  <ul class="nav nav-list">
    <li><%= link_to "Active Sites", sites_path %></li>
    <li></li>
  </ul>

<% end %>

<div class="well">
  <h1>Archived Sites</h1>
</div>

<% @sites.each_slice(3) do |row| %>
  <div class="row-fluid">
    <% row.each do |site| %>
      <div class="span4">
        <div class="well tile">
          <%= link_to site do %>
            <h2><%= site.name %></h2>
            <span>
              <%= link_to "unarchive", unarchive_site_path(site), :method => :put %>
            </span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>


<%= paginate @sites %>

app/views/sites/create.html.erb
<h1>Sites#create</h1>
<p>Find me in app/views/sites/create.html.erb</p>

app/views/sites/destroy.html.erb
<h1>Sites#destroy</h1>
<p>Find me in app/views/sites/destroy.html.erb</p>

app/views/sites/edit.html.erb
<h1>Sites#edit</h1>
<p>Find me in app/views/sites/edit.html.erb</p>

app/views/sites/index.html.erb
<% content_for :sidebar do %>

  <h3>Site</h3>
  <ul class="nav nav-list">
    <li>
      <%= link_to "Add New Site", new_site_path %>
    </li>
    <li>
      <%= link_to "Archived Sites", archived_sites_path %>
    </li>
  </ul>

<% end %>

<% content_for :title, "sites" %>

<ul class="tiled">
  <% @sites.each do |site| %>
    <li>
      <div>
        <%= link_to site do %>
          <h2><%= site.name %></h2>
        <% end %>
        <div class="extra-actions">
          <%= link_to "archive", archive_site_path(site), :confirm => "Are you sure you want to archive this site ?", :method => :put %>
        </div>
      </div>
    </li>
  <% end %>

  <li class="add">
    <div>
      <%= link_to new_site_path do %>
        <h2>Add a site</h2>
      <% end %>
    </div>
  </li>
</ul>


<%= paginate @sites %>

app/views/sites/new.html.erb
<% content_for :title, "New site" %>

<%= form_for @site, :url => sites_path, :html => {:class => "form-horizontal"}  do |form| %>

  <fieldset>
    <%= render :partial => "shared/errors", locals: { object: @site} %>    
    <%= render :partial => "sites/form", locals: { form: form} %>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Create!</button>
    </div>

  </fieldset>

<% end %>

app/views/sites/show.html.erb
<% content_for :title, "api methods" %>

<ul class="primary-content">
  <% @site.api_methods.each do |api_method| %>
    <li> <%= link_to api_method.name, [@site, api_method] %>
  <% end %>
  <li class="add">
    <%= link_to "add an api method", new_site_api_method_path(@site) %>
  </li>
</ul>

app/views/sites/update.html.erb
<h1>Sites#update</h1>
<p>Find me in app/views/sites/update.html.erb</p>