config/routes.rb
WebadapterPrototype::Application.routes.draw do

  devise_for :users

  resources :sites do
    get 'page/:page', :action => :index, :on => :collection
    match 'api/:name', :to => "api_methods#call", :as => 'api_method_call'

    resources :api_methods do
      member do
        get 'call'
      end

      resources :versions do
        member do
          put 'restore'
        end
      end

      resources :alarms
    end

    member do
      put :archive
      put :unarchive
    end

    collection do
      get :archived
    end

  end

  resources :users do
    member do
      put :disable
      put :enable
    end
  end

  resources :alarms

  root :to => 'sites#index'
end

app/views/layouts/_flash.html.erb
<% if alert %>
  <div class="alert alert-error">
    <strong>:(</strong>
    <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-success">
    <strong>Yay!</strong>
    <%= notice %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    &copy; 2012 Velti plc and its subsidiaries.
  </p>
</footer>

app/views/layouts/_navigation.html.erb
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Webadapter 2", root_url, :class => "brand" %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Sites", sites_path  %></li>
              <% if @site %>
              <li><p class="navbar-text">/</p></li>
              <li><%= link_to @site.name, @site %></li>
              <% if @api_method %>
              <li><p class="navbar-text">/</p></li>
              <li><%= link_to @api_method.name, [@site, @api_method] %></li>
              <% end %>
              <% end %>
            </ul>
          <% if current_user %>
            <ul class="nav pull-right">
              <li><%= link_to "Alarms", alarms_url %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= current_user.email %>
                  <b class="caret"></b>
                </a>

                <ul class="dropdown-menu">
                <li>
                  <%= link_to "Edit profile", edit_user_path(current_user) %>
                </li>
                <li>
                  <%= link_to "Manage users", users_path %>
                </li>
                <li class="divider"></li>                
                <li>
                  <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
                </li>
                </ul>
              </li>
            </ul>
          <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/_sidebar.html.erb
<div class="well sidebar-nav">
  <%= yield :sidebar %>
</div><!--/.well -->

app/views/layouts/_title.html.erb
<h1>
  <% if @site && ! @site.new_record? %>
    <%= link_to "sites", sites_path %> &raquo;
    <%= link_to @site.name, @site %> &raquo;
  <% end %>
  <% if @api_method && ! @api_method.new_record? && url_for([@site, @api_method]) != request.fullpath %>
    <%= link_to @api_method.name, [@site, @api_method] %> &raquo;
  <% end %>
  <span class="title">
    <%= yield :title %>
    //
  </span>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Webadapter</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>
    <% if user_signed_in? -%>
      <div id="login">
        <ul>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.email %>
              <b class="caret caret-white"></b>
            </a>

            <ul class="dropdown-menu">
            <li>
              <%= link_to "Edit profile", edit_user_path(current_user) %>
            </li>
            <li>
              <%= link_to "Manage users", users_path %>
            </li>
            <li class="divider"></li>                
            <li>
              <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
            </li>
            </ul>
          </li>
        </ul>
      </div>
    <% end -%>

    <div id="panel-branding">
      <div id="brand-logo">
        <%= link_to root_path do %>
          <%= image_tag 'velti_white.png' %>
        <% end %>
      </div>
      <h1 id="product-logo">
        <%= link_to root_path do %>
          Webadapter
        <% end %>
      </h1>
      <div id="copyright">
        <p>
          &copy; 2012 Velti plc and its subsidiaries.
        </p>
      </div>
    </div>

    <div id="panel-main">
      <%= render "layouts/title" %>
      <%= render :partial => "layouts/flash" %>
      <%= yield %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/ide.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Webadapter 2</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body class="ide">

  <%= render :partial => "layouts/flash" %>

    <div class="container-fluid">
      <div class="content">
        <%= yield %>
      </div><!--/content-->
    </div> <!-- /container -->

    <footer>
      <div class="branding">
        <div id="brand-logo">
          <%= link_to root_path do %>
            <%= image_tag 'velti_rgb.png' %>
          <% end %>
        </div>
        <h1 id="product-logo">
          <%= link_to root_path do %>
            Webadapter
          <% end %>
        </h1>
      </div>
      <div id="copyright">
        <p>
          &copy; 2012 Velti plc and its subsidiaries.
        </p>
      </div>
    </footer>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>